void clipare_init(void);
int clipare_poll(void);
int clipare_view(void);
int clipare_disclosures(void);
void clipare_sync_status(int state,const char *message,const char *reason);
void clipare_device_rows(const char *json,int empty,int list,int remove,int compact);
void clipare_show(void);
void clipare_set(int index,const char *text);
char *clipare_get(int index);
void clipare_auto(int enabled);
int clipare_is_auto(void);
void clipare_preferences(int autostart,int updates);
void clipare_addresses(const char *lines);
void clipare_peers(const char *lines);
int clipare_selected(void);
void clipare_status(const char *status,int enabled,const char *peers);
void clipare_alert(const char *text);
void clipare_close(void);
void clipare_discovered(const char *lines,const char *status);
int clipare_discovered_selected(void);
void clipare_pair(const char *name,const char *sas,int incoming);
void clipare_pair_close(void);
void clipare_update_settings(const char *version,int enabled);
int clipare_update_enabled(void);
void clipare_update_prompt(const char *text,const char *primary,const char *dismiss,int action);
void clipare_update_close(void);
